# Generated by Django 4.2.7 on 2025-10-29 15:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(upload_to=core.models.get_upload_path),
                ),
                (
                    "dehazed_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.get_output_path
                    ),
                ),
                (
                    "detection_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.get_output_path
                    ),
                ),
                ("is_hazy", models.BooleanField(default=False)),
                ("haze_confidence", models.FloatField(default=0.0)),
                ("processing_time", models.FloatField(default=0.0)),
                ("original_psnr", models.FloatField(blank=True, null=True)),
                ("enhanced_psnr", models.FloatField(blank=True, null=True)),
                ("original_ssim", models.FloatField(blank=True, null=True)),
                ("enhanced_ssim", models.FloatField(blank=True, null=True)),
                ("objects_detected_before", models.IntegerField(default=0)),
                ("objects_detected_after", models.IntegerField(default=0)),
                ("detection_improvement", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
