# Generated by Django 4.2.7 on 2025-10-29 19:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingresult",
            name="detection_enhanced",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.get_output_path
            ),
        ),
        migrations.AddField(
            model_name="processingresult",
            name="detection_original",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.get_output_path
            ),
        ),
    ]
